version: '3.8'

services:
  # 1. Ứng dụng Web Next.js
  nextjs-app:
    image: ghcr.io/saodonga/aptmayin:latest
    container_name: printer_server_app
    restart: always
    ports:
      - "8028:3500"
    env_file:
      - .env
    volumes:
      - temp-print-files:/app/temp
    depends_on:
      - cups-server

  # 2. CUPS Print Server (Đầu não kết nối máy in USB và máy in mạng)
  cups-server:
    image: olbat/cupsd:latest
    container_name: printer_cups_server
    privileged: true # Cần thiết để nhận cổng USB trên máy chủ Linux Host
    restart: always
    ports:
      - "6315:631"
    volumes:
      - /var/run/dbus:/var/run/dbus  # Hỗ trợ tự động dò quét máy in
      - /dev/bus/usb:/dev/bus/usb    # Map cổng USB máy host vào container
      - cups-config:/etc/cups        # Lưu trữ cấu hình máy in CUPS
      - cups-spool:/var/spool/cups   # Lưu trữ hàng đợi in
    environment:
      - ADMIN_PASSWORD=admin_secret

volumes:
  temp-print-files:
  cups-config:
  cups-spool:
